### ISSUE TITLE
Je n'arrive pas à initialiser l'etat sur une sortie

### ISSUE THREAD

**Issue by thomasLores** [iOuls/projetSortir.com#13]
@caliendojulien

**Comment by caliendojulien** [comment]
@thomasLores  Tu es sur quelle branche ? Tu l'as push ?

**Comment by caliendojulien** [comment]
@thomasLores :

J'ai regardé la branche TL_branche_3 et j'ai pas trop compris les entités.

Dans Site.php, c'est quoi ce :
`#[ORM\ManyToOne(inversedBy: 'Site')] private ?Filtre $filtre = null;`
Je ne vois aucune entité Filtre.

Autre chose, dans l'entité Sortie.php tu as un manyToMany sur l'attribut participants mais dans l'autre sens (dans User sur l'attribut sorties) c'est un OneToMany. C'est pas possible.

@iOuls @Thibautsansl Je pense qu'il faut revoir vos entités.

**Comment by thomasLores** [comment]
je n'avais pas push l'entité filtre...
Mais mon problème c'est que quand je veux créer une sortie, j'ai se message d'erreur "Call to a member function setLibelle() on null". En gros, je n'arrive pas à renseigner l'etat de la sortie.
