### ISSUE TITLE
2007 - Archiver les sorties

### ISSUE THREAD

**Issue by iOuls** [iOuls/projetSortir.com#3]
@caliendojulien pour le ticket 2007 - Archiver les sorties

"Les sorties réalisées depuis plus d’un mois ne sont pas consultables."

Les sorties ne sont pas consultables par qui ? Partout ? ça manque cruellement de précision M le PO !

**Comment by caliendojulien** [comment]
- Consultables par personne a part l'administrateur
- Oui, partout. A part dans le panneau admin.
