### ISSUE TITLE
Récupération profil

### ISSUE THREAD

**Issue by Thibautsansl** [iOuls/projetSortir.com#9]
Quand je suis connecter avec mon compte, je veut voir les champs préremplis quand je vais dans mon profil, je penser avoir fait la bonne méthode dans le ProfilController mais apparemment non. Peux-tu y jeter un coup d'œil stp.

Dans la branche TG-branche

**Comment by caliendojulien** [comment]
@Thibautsansl Ta branche doit être "push" pour que je puisse la voir et travailler dessus.

**Comment by Thibautsansl** [comment]
ah of corsse
